version: '3.10'

services:
  api:
    platform: Linux/arm64
    build: .
    volumes:
      - .:/cheshirewestvehicles
    ports:
      - 8000:8000
    image: api:cheshirewestvehicles
    container_name: cwv_api_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
    - ./frontend:/frontend

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - '.env'
    container_name: postgres_db