# Generated by Django 4.1.4 on 2023-02-05 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0005_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='business_admin.customer'),
        ),
    ]
