# Generated by Django 4.1.4 on 2023-03-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0007_alter_customer_customer_id_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
