# Generated by Django 4.1.4 on 2023-03-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_admin', '0008_invoice_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='line_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
