# Generated by Django 4.1.4 on 2022-12-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='paymentIntent_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
