# Generated by Django 4.1.4 on 2022-12-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_tradein_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='paymentIntent_id',
            new_name='charge_id',
        ),
    ]
