# Generated by Django 4.1.4 on 2022-12-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_paymentintent_id_reservations_charge_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='reservations',
            old_name='charge_id',
            new_name='paymentIntent_id',
        ),
    ]
